# Generated by Django 5.0.3 on 2025-03-24 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='answer',
            new_name='query',
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='question',
            new_name='response',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='has_pii',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='analysis',
            name='report',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='document_type',
            field=models.CharField(choices=[('RFP', 'Request for Proposal'), ('RESPONSE', 'Response Document')], max_length=10),
        ),
        migrations.AlterField(
            model_name='document',
            name='faiss_index_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
