# Generated by Django 5.0.3 on 2025-03-25 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chatmessage',
            old_name='question',
            new_name='query',
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pii_detected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pii_recommendations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='pii_risk_level',
            field=models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('UNKNOWN', 'Unknown')], default='UNKNOWN', max_length=20),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
